language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
  - wget_cache
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
before_install:
  -  gem update --system 2.1.11
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec
notifications:
  email:
    - boris@seekingalpha.com
env:
  - PUPPET_GEM_VERSION=4.8.2 FIXTURES_YML=.fixtures-oldapt.yml
  - PUPPET_GEM_VERSION=4.8.2
  - PUPPET_GEM_VERSION=4.9.4
  - PUPPET_GEM_VERSION=4.10.11
  - PUPPET_GEM_VERSION=5.3.6
  - PUPPET_GEM_VERSION=5.5.1
matrix:
  exclude:
    - rvm: 2.2.10
      env: PUPPET_GEM_VERSION=5.5.1
